== Application
plantuml::components.puml[,,format=svg]

== Shared
plantuml::module-shared.puml[,,format=svg]
include::module-shared.adoc[]

== Settings
plantuml::module-settings.puml[,,format=svg]
include::module-settings.adoc[]

== Storeprofile
plantuml::module-storeprofile.puml[,,format=svg]
include::module-storeprofile.adoc[]

== User
plantuml::module-user.puml[,,format=svg]
include::module-user.adoc[]

== Member
plantuml::module-member.puml[,,format=svg]
include::module-member.adoc[]

== Menu
plantuml::module-menu.puml[,,format=svg]
include::module-menu.adoc[]

== Notification
plantuml::module-notification.puml[,,format=svg]
include::module-notification.adoc[]

== Point
plantuml::module-point.puml[,,format=svg]
include::module-point.adoc[]

== Storage
plantuml::module-storage.puml[,,format=svg]
include::module-storage.adoc[]

== Auth
plantuml::module-auth.puml[,,format=svg]
include::module-auth.adoc[]

== Customer
plantuml::module-customer.puml[,,format=svg]
include::module-customer.adoc[]

== Store
plantuml::module-store.puml[,,format=svg]
include::module-store.adoc[]

== Cast
plantuml::module-cast.puml[,,format=svg]
include::module-cast.adoc[]

== Shift
plantuml::module-shift.puml[,,format=svg]
include::module-shift.adoc[]

== Order
plantuml::module-order.puml[,,format=svg]
include::module-order.adoc[]

