@startuml
set separator none
title Auth

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("Application.Application_boundary", "Application", $tags="") {
  Component(Application.Application.Shared, "Shared", $techn="Module", $descr="", $tags="", $link="")
  Component(Application.Application.User, "User", $techn="Module", $descr="", $tags="", $link="")
  Component(Application.Application.Auth, "Auth", $techn="Module", $descr="", $tags="", $link="")
}

Rel(Application.Application.Auth, Application.Application.User, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.Auth, Application.Application.Shared, "uses", $techn="", $tags="", $link="")
Rel(Application.Application.User, Application.Application.Shared, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml